project:
  type: website
  output-dir: docs

website:
  title: "Lara Space"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - blog.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  
  
    

format:
  html:
    theme: pulse
    css: styles.css
    toc: true



